### ISSUE TITLE
Logs don't show on try results page

### ISSUE THREAD

**Issue by athomas** [dart-lang/dart_ci#79]
https://dart-ci.firebaseapp.com/cl/137060/2 shows "Logs" popups that are empty (No links).

Seems to be some sort of NPE:
```
stacktrace.dart:60 EXCEPTION: NoSuchMethodError: method not found: 'c' on null
STACKTRACE: 
TypeError: Cannot read property 'c' of null
    at as.ev (https://dart-ci.firebaseapp.com/main.dart.js:20741:58)
    at mp.u (https://dart-ci.firebaseapp.com/main.dart.js:21098:5)
    at mp.G (https://dart-ci.firebaseapp.com/main.dart.js:13772:11)
    at x.A (https://dart-ci.firebaseapp.com/main.dart.js:13621:6)
    at rq.u (https://dart-ci.firebaseapp.com/main.dart.js:21088:5)
    at rq.G (https://dart-ci.firebaseapp.com/main.dart.js:13772:11)
    at x.A (https://dart-ci.firebaseapp.com/main.dart.js:13621:6)
    at rp.u (https://dart-ci.firebaseapp.com/main.dart.js:21070:5)
    at rp.G (https://dart-ci.firebaseapp.com/main.dart.js:13772:11)
    at x.A (https://dart-ci.firebaseapp.com/main.dart.js:13621:6)
```

Maybe this is because this is a new configuration?

**Comment by athomas** [comment]
The logs show up now that the change was landed. I'm pretty sure this is because it was a new config. That's not a very common case, so I'm reducing this to P3.
